class SERVER_STATUS_TYPE:
    S_SERVER_STATE_DEV_KEY = "S_SERVER_STATE"
    S_SERVER_STATE_DEV = "dev"
    S_SERVER_STATE_PRODUCTION_1 = "production_server_1"
    S_SERVER_STATE_PRODUCTION_2 = "production_server_2"
