version: '3'
services:
  web:
    build: .
    ports:
      - "8070:8070"
    depends_on:
      - elasticsearch
      - mongodb
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9400
      - MONGO_URI=mongodb://mongodb:27017/genesisdb

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - http.port=9400
      - ELASTIC_PASSWORD=Imammehdi@00
    ports:
      - "9400:9400"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 5G

  mongodb:
    image: mongo:5.0
    ports:
      - "27020:27017"
    volumes:
      - mongodata:/data/db
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  esdata:
  mongodata:
