version: '3'
services:
  web:
    build: .
    ports:
      - "8070:8070"
    depends_on:
      - elasticsearch
      - mongodb
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MONGO_URI=mongodb://mongodb:27017/genesisdb

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - http.port=9200
      - ELASTIC_PASSWORD=Imammehdi@00
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  esdata:
  mongodata:
