version: '3'
services:
  web:
    container_name: trusted-web
    build:
      context: .
      dockerfile: dockerFiles/api_docker
    depends_on:
      - elasticsearch
      - mongodb
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --no-input || true &&
             python manage.py cronjob_manager &
             gunicorn trustly.wsgi:application --bind 0.0.0.0:8070"
    volumes:
      - static_volume:/app/static
    expose:
      - "8070"

  nginx:
    container_name: trusted-web-nginx
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static

  elasticsearch:
    container_name: trusted-web-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - http.port=9400
      - ELASTIC_USERNAME=${ELASTIC_ROOT_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_ROOT_PASSWORD}
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    env_file:
      - .env
    ports:
      - "9400:9400"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 5G

  mongodb:
    image: mongocamp/mongodb:5.0.9
    container_name: trusted-web-mongo
    env_file:
      - .env
    command: mongod --auth --quiet --logpath /dev/null
    logging:
      driver: none
    volumes:
      - ./data/db:/data/db
    ports:
      - "27020:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  esdata:
  mongodata:
  static_volume:
