
# General
class GENERAL_STRINGS:
    S_GENERAL_EMPTY = ""
    S_GENERAL_EMPTY_SPACE = " "
    S_GENERAL_ONION_DOMAIN = ".onion"
    S_GENERAL_HTTP = "http"
    S_GENERAL_CONTENT_CONTINUE = " ..."

# Sitemap
class SITEMAP_STRINGS:
    S_SITEMAP_SUBMISSION_RULE_1 = "New Onion Service"
    S_SITEMAP_SUBMISSION_RULE_2 = "Update Onion Service"
    S_SITEMAP_RULE_DEFAULT_STATE = "checked"

# Search
class SEARCH_STRINGS:
    S_SEARCH_TYPE_PARAM = "all"
    S_SEARCH_CONTENT_TYPE_IMAGE = "images"
    S_SEARCH_CONTENT_TYPE_DOCUMENT = "doc"
