import enum


class TOPIC_CLASSFIER_COMMANDS(enum.Enum):
    S_LOAD_CLASSIFIER = 1
    S_PREDICT_CLASSIFIER = 2

class TOPIC_CLASSFIER_MODEL(enum.Enum):
    S_LOAD_CLASSIFIER = 1
    S_PREDICT_CLASSIFIER = 2

class TOPIC_CLASSFIER_TRAINER(enum.Enum):
    S_CLEAN_DATA = 2

class TOPIC_CLASSFIER_MESSAGES:
    S_CLASSIFIER_NOT_TRAINED = "CLASSIFIER NOT TRAINIED"